module.exports=
    name:"火焰纹章：风花雪月"
    #
    opening:"新的课题开始了。"
    # to let players know woh they are
    skin_tip:"你的身份"
    # 主题的作者
    author:"2336489322"
    # 修改时间
    lastModified:"2025-07-10T12:06:13.448204"
    vote:"aaaa"
    sunrise:"bbbbbb"
    sunset:"cccccc"
    icon:""
    background_color:"black"
    color:"rgb(255,0,166)"
    lockable:true
    isAvailable:->
        # 如果想要做成有某种限制条件
        # return false
        return true
    skins:
        # 罗马字名 ，只允许半角英数字和下划线，数字和下划线不允许是首位
        # 不可以重复
        BylethM:
            avatar:"https://s2.loli.net/2025/07/11/VKbLBYS4x3syzFA.jpg"
            name:"贝雷特"
            prize:"老师的引导"
        BylethF:
            avatar:"https://s2.loli.net/2025/07/11/dAfmkUKh4jeou3I.jpg"
            name:"贝雷丝"
            prize:"老师的引导"
        Edelgard:
            avatar:"https://s2.loli.net/2025/07/11/g75mOxEbWSXsQyz.jpg"
            name:"艾黛尔贾特"
            prize:"皇帝的血统"
        Dimitri:
            avatar:"https://s2.loli.net/2025/07/11/3HrTXFGuDhcmxft.jpg"
            name:"帝弥托利"
            prize:"王之血统"
        Claude:
            avatar:"https://s2.loli.net/2025/07/11/5enXbIDJY1dkCjt.jpg"
            name:"库罗德"
            prize:"盟主的血统"
        Sothis:
            avatar:"https://s2.loli.net/2025/07/11/vW6pyACaQTJd8c4.png"
            name:"苏谛斯"
            prize:"女神"
        Rhea:
            avatar:"https://s2.loli.net/2025/07/11/vrhqbgNa8YOMJCI.png"
            name:"蕾雅"
            prize:"大司教"
        Jeralt:
            avatar:"https://s2.loli.net/2025/07/11/OIN9omCcwXVAY3p.png"
            name:"杰拉尔特"
            prize:"骑士团长"
        Hubert:
            avatar:"https://s2.loli.net/2025/07/11/4tuAq3sTrm8EF1Y.png"
            name:"修伯特"
            prize:"参谋"
        Ferdinand:
            avatar:"https://s2.loli.net/2025/07/11/fSbFrT6AhD5gytK.png"
            name:"菲尔迪南特"
            prize:"胸有成竹"
        Dorothea:
            avatar:"https://s2.loli.net/2025/07/11/RUJdNTs8ilg2Kwy.png"
            name:"多洛缇雅"
            prize:"歌姬"
        Dedue:
            avatar:"https://s2.loli.net/2025/07/11/jcq6IPGMEC7LQBX.png"
            name:"杜笃"
            prize:"君主之盾"
        Felix:
            avatar:"https://s2.loli.net/2025/07/11/bzhNoOYVuSw45yP.png"
            name:"菲力克斯"
            prize:"独狼"
        Lorenz:
            avatar:"https://s2.loli.net/2025/07/11/aV2Uk53YETRilt9.png"
            name:"洛廉兹"
            prize:"名门贵族"
        Hilda:
            avatar:"https://s2.loli.net/2025/07/11/asXhLuBTqCoMyF1.png"
            name:"希尔妲"
            prize:"撒娇"
        Hanneman:
            avatar:"https://s2.loli.net/2025/07/11/Us8yXV2BzKSTH6R.png"
            name:"汉尼曼"
            prize:"纹章学者"
        Manuela:
            avatar:"https://s2.loli.net/2025/07/11/cotAlzudOaC9iKf.png"
            name:"玛努艾拉"
            prize:"医务室之主"
        Anna:
            avatar:"https://s2.loli.net/2025/07/11/oW2RyXMimt5h7uS.png"
            name:"安娜"
            prize:"生意兴隆"
        Mercedes:
            avatar:"https://s2.loli.net/2025/07/11/8XkYG5nNhgWEcfy.png"
            name:"梅尔赛德司"
            prize:"奉献之喜"
        Raphael:
            avatar:"https://s2.loli.net/2025/07/11/sH34FvLCXoOyDVe.png"
            name:"拉斐尔"
            prize:"捡拾"
        Ashe:
            avatar:"https://s2.loli.net/2025/07/11/FKsENrbJwSGm1q7.png"
            name:"亚修"
            prize:"生存的智慧"
        Bernadetta:
            avatar:"https://s2.loli.net/2025/07/11/PAixeZGSlFV9TKp.png"
            name:"贝尔娜提塔"
            prize:"被害妄想"
        Lysithea:
            avatar:"https://s2.loli.net/2025/07/11/qDczdTKyJArQPa4.png"
            name:"莉丝缇亚"
            prize:"天才"
        Caspar:
            avatar:"https://s2.loli.net/2025/07/11/7l4Mr6QjKmqOPkd.png"
            name:"卡斯帕尔"
            prize:"好勇斗狠"
        Annette:
            avatar:"https://s2.loli.net/2025/07/11/DQiAzcqIwty6exk.png"
            name:"雅妮特"
            prize:"拼命三郎"
        Ignatz:
            avatar:"https://s2.loli.net/2025/07/11/RXBhldVIzZw1yfG.png"
            name:"伊古纳兹"
            prize:"洞察之眼"
        Petra:
            avatar:"https://s2.loli.net/2025/07/11/y3fUnPGpVoHXd5c.png"
            name:"佩托拉"
            prize:"狩猎的守则"
        Sylvain:
            avatar:"https://s2.loli.net/2025/07/11/WpnFblf4DMdB9c8.png"
            name:"希尔凡"
            prize:"花花公子"
        Marianne:
            avatar:"https://s2.loli.net/2025/07/11/cYETkKoVe71rQvW.png"
            name:"玛丽安奴"
            prize:"热爱动物"
        Catherine:
            avatar:"https://s2.loli.net/2025/07/11/kMB1TdltUKYhsyH.png"
            name:"卡多莉奴"
            prize:"斗魂"
        Linhardt:
            avatar:"https://s2.loli.net/2025/07/11/3QIupxc2869SJrY.png"
            name:"林哈尔特"
            prize:"小睡片刻"
        Ingrid:
            avatar:"https://s2.loli.net/2025/07/11/yMAJK2GRt4nUh6P.png"
            name:"英谷莉特"
            prize:"女骑士"
        Leonie:
            avatar:"https://s2.loli.net/2025/07/11/qFpdH1JgRZ35exr.png"
            name:"雷欧妮"
            prize:"争强好胜"
        Alois:
            avatar:"https://s2.loli.net/2025/07/11/xpBRuzUSrXGw7qi.png"
            name:"阿罗伊斯"
            prize:"老好人"
        Seteth:
            avatar:"https://s2.loli.net/2025/07/11/dJVO7av9wMQyLsA.png"
            name:"西提司"
            prize:"过度保护"
        Flayn:
            avatar:"https://s2.loli.net/2025/07/11/L65HEgwVrGQtCFh.png"
            name:"芙莲"
            prize:"惹人怜爱的花朵"
        Jeritza:
            avatar:"https://s2.loli.net/2025/07/11/FZjOsD3B8fPQSqX.png"
            name:"伊艾里扎"
            prize:"杀意"
        Gilbert:
            avatar:"https://s2.loli.net/2025/07/11/ezRhHPFYoBX3xct.png"
            name:"吉尔伯特"
            prize:"身经百战的骑士"
        Shamir:
            avatar:"https://s2.loli.net/2025/07/11/a1edHkbSqK7pOL5.png"
            name:"萨米亚"
            prize:"生存本能"
        Cyril:
            avatar:"https://s2.loli.net/2025/07/11/raORe3dGXUlIfLv.png"
            name:"锥里尔"
            prize:"天赋过人"
        Yuri:
            avatar:"https://s2.loli.net/2025/07/11/TmNXopOFh9JEjzS.png"
            name:"尤里斯"
            prize:"侠义心"
        Balthus:
            avatar:"https://s2.loli.net/2025/07/11/SiG8LVmFbxl1O32.png"
            name:"巴鲁塔扎尔"
            prize:"格斗王"
        Constance:
            avatar:"https://s2.loli.net/2025/07/11/1SK2Nj6lzpIL8qH.png"
            name:"康斯坦洁"
            prize:"性格突变"
        Hapi:
            avatar:"https://s2.loli.net/2025/07/11/3U5gCu2GB4PAIkZ.png"
            name:"哈琵"
            prize:"魔物体质"
